"""AIOS Knowledge Endpoints."""

import structlog
from typing import List, Optional
from fastapi import APIRouter, HTTPException, Query

from aios.schemas.knowledge import KnowledgeSearch, KnowledgeIndex, KnowledgeResponse

logger = structlog.get_logger(__name__)

router = APIRouter()

# In-memory store for now
_knowledge_entries: dict = {}


@router.get("/search", response_model=List[KnowledgeResponse])
async def search_knowledge(
    query: str = Query(..., min_length=1),
    limit: int = Query(10, ge=1, le=100),
    source: Optional[str] = None,
) -> List[KnowledgeResponse]:
    """Search knowledge base with semantic search."""
    results = []
    for entry in _knowledge_entries.values():
        if source and entry.get("source") != source:
            continue
        if query.lower() in entry.get("content", "").lower():
            results.append(KnowledgeResponse(**entry))
        if len(results) >= limit:
            break
    return results


@router.post("/index", response_model=KnowledgeResponse, status_code=201)
async def index_document(doc: KnowledgeIndex) -> KnowledgeResponse:
    """Index a document into the knowledge base."""
    import uuid
    from datetime import datetime
    
    doc_id = str(uuid.uuid4())
    doc_data = {
        "id": doc_id,
        "source": doc.source,
        "content": doc.content,
        "metadata": doc.metadata or {},
        "embedding": None,  # Will be generated by indexing system
        "indexed_at": datetime.utcnow().isoformat(),
    }
    _knowledge_entries[doc_id] = doc_data
    logger.info("Document indexed", doc_id=doc_id, source=doc.source)
    return KnowledgeResponse(**doc_data)


@router.get("/{doc_id}", response_model=KnowledgeResponse)
async def get_knowledge(doc_id: str) -> KnowledgeResponse:
    """Get a knowledge entry by ID."""
    if doc_id not in _knowledge_entries:
        raise HTTPException(status_code=404, detail="Knowledge entry not found")
    return KnowledgeResponse(**_knowledge_entries[doc_id])


@router.delete("/{doc_id}", status_code=204)
async def delete_knowledge(doc_id: str) -> None:
    """Delete a knowledge entry."""
    if doc_id not in _knowledge_entries:
        raise HTTPException(status_code=404, detail="Knowledge entry not found")
    del _knowledge_entries[doc_id]
    logger.info("Knowledge entry deleted", doc_id=doc_id)
