"""AIOS Memory Endpoints."""


import structlog
from fastapi import APIRouter, HTTPException, Query

from aios.schemas.memory import MemoryResponse, MemoryStore

logger = structlog.get_logger(__name__)

router = APIRouter()

# In-memory store for now
_memories: dict = {}


@router.get("/search", response_model=list[MemoryResponse])
async def search_memory(
    query: str = Query(..., min_length=1),
    limit: int = Query(10, ge=1, le=100),
    memory_type: str | None = None,
) -> list[MemoryResponse]:
    """Search memory with semantic search."""
    # Placeholder for semantic search
    results = []
    for mem in _memories.values():
        if memory_type and mem.get("type") != memory_type:
            continue
        if query.lower() in mem.get("content", "").lower():
            results.append(MemoryResponse(**mem))
        if len(results) >= limit:
            break
    return results


@router.post("/store", response_model=MemoryResponse, status_code=201)
async def store_memory(memory: MemoryStore) -> MemoryResponse:
    """Store a memory entry."""
    import uuid
    from datetime import datetime

    memory_id = str(uuid.uuid4())
    memory_data = {
        "id": memory_id,
        "type": memory.type,
        "content": memory.content,
        "metadata": memory.metadata or {},
        "embedding": None,  # Will be generated by indexing system
        "created_at": datetime.utcnow().isoformat(),
        "updated_at": datetime.utcnow().isoformat(),
    }
    _memories[memory_id] = memory_data
    logger.info("Memory stored", memory_id=memory_id, type=memory.type)
    return MemoryResponse(**memory_data)


@router.get("/{memory_id}", response_model=MemoryResponse)
async def get_memory(memory_id: str) -> MemoryResponse:
    """Get a memory by ID."""
    if memory_id not in _memories:
        raise HTTPException(status_code=404, detail="Memory not found")
    return MemoryResponse(**_memories[memory_id])


@router.delete("/{memory_id}", status_code=204)
async def delete_memory(memory_id: str) -> None:
    """Delete a memory entry."""
    if memory_id not in _memories:
        raise HTTPException(status_code=404, detail="Memory not found")
    del _memories[memory_id]
    logger.info("Memory deleted", memory_id=memory_id)
